# Generated by Django 5.1.4 on 2026-08-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchgearitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='switchgear/items/'),
        ),
    ]
