# Generated by Django 5.1.4 on 2026-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_switchgearitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meters/features/'),
        ),
    ]
