# Generated by Django 5.1.4 on 2026-08-30 17:57

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_meterfeature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchgearitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (HY)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (RU)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='fuse_table',
            field=models.TextField(blank=True, help_text='Optional fuse-selection matrix as JSON.'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='switchgear/docs/', verbose_name='Instruction PDF'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='purpose_en',
            field=models.TextField(blank=True, verbose_name='Purpose (EN)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='purpose_hy',
            field=models.TextField(blank=True, verbose_name='Purpose (HY)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='purpose_ru',
            field=models.TextField(blank=True, verbose_name='Purpose (RU)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='spec_cols',
            field=models.CharField(blank=True, help_text='Voltage column headers, separated by ·  e.g. 12 · 17.5 · 24', max_length=120),
        ),
        migrations.AlterField(
            model_name='switchgearitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='switchgear/items/', verbose_name='Cover image'),
        ),
        migrations.CreateModel(
            name='SwitchgearItemBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this item from the website (draft).')),
                ('kind', models.CharField(choices=[('equipment', 'Standard equipment'), ('option', 'Option'), ('vacuum', 'Vacuum-breaker option')], default='equipment', max_length=16)),
                ('text_hy', models.TextField(blank=True, verbose_name='Text (HY)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Text (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Text (EN)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='content.switchgearitem')),
            ],
            options={
                'verbose_name': 'Switchgear item bullet',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
            bases=(content.models.TriMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchgearItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this item from the website (draft).')),
                ('image', models.ImageField(upload_to='switchgear/items/gallery/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.switchgearitem')),
            ],
            options={
                'verbose_name': 'Switchgear item image',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwitchgearItemSpecRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this item from the website (draft).')),
                ('param_hy', models.CharField(blank=True, max_length=255, verbose_name='Parameter (HY)')),
                ('param_ru', models.CharField(blank=True, max_length=255, verbose_name='Parameter (RU)')),
                ('param_en', models.CharField(blank=True, max_length=255, verbose_name='Parameter (EN)')),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('v1', models.CharField(blank=True, max_length=60, verbose_name='Value 1')),
                ('v2', models.CharField(blank=True, max_length=60, verbose_name='Value 2')),
                ('v3', models.CharField(blank=True, max_length=60, verbose_name='Value 3')),
                ('is_group', models.BooleanField(default=False, help_text='Render as a sub-heading row (e.g. “Module dimensions”).')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_rows', to='content.switchgearitem')),
            ],
            options={
                'verbose_name': 'Switchgear item spec row',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
            bases=(content.models.TriMixin, models.Model),
        ),
    ]
