# Generated by Django 5.1.4 on 2026-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_switchgearitem_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchgearitem',
            name='notes_en',
            field=models.TextField(blank=True, verbose_name='Spec footnotes (EN)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='notes_hy',
            field=models.TextField(blank=True, verbose_name='Spec footnotes (HY)'),
        ),
        migrations.AddField(
            model_name='switchgearitem',
            name='notes_ru',
            field=models.TextField(blank=True, verbose_name='Spec footnotes (RU)'),
        ),
    ]
