# -*- coding: utf-8 -*-
"""
UI string bundle transcribed from site/assets/js/i18n.js.

Each value is a tuple ``(hy, ru, en)``. Seeded into the ``UIString`` model so
the owner can edit every label/heading from the admin. `meta.dir` is included
so the frontend keeps setting <html dir> from live data.
"""

UI_STRINGS = {
    "meta.dir": ("ltr", "ltr", "ltr"),
    "brand.name": ("ԿԱՍԿԱԴ", "КАСКАД", "KASKAD"),
    "brand.suffix": ("ԳՐՈՒՊ", "ГРУПП", "GROUP"),
    "brand.tagline": ("Փոխակերպումների էներգիա", "Энергия преобразований", "Energy of Transformations"),

    "nav.home": ("Գլխավոր", "Главная", "Home"),
    "nav.construction": ("Շինարարություն", "Строительство", "Construction"),
    "nav.switchgear": ("Բաշխիչ սարքեր", "Распредустройства", "Switchgear"),
    "nav.meters": ("Հաշվիչներ", "Счётчики", "Meters"),
    "nav.about": ("Մեր մասին", "О компании", "About"),
    "nav.projects": ("Նախագծեր", "Проекты", "Projects"),
    "nav.products": ("Արտադրանք", "Продукция", "Products"),
    "nav.contact": ("Կապ", "Контакты", "Contact"),
    "nav.divisions": ("Ուղղություններ", "Направления", "Divisions"),

    "cta.more": ("Մանրամասն", "Подробнее", "Learn more"),
    "cta.allProjects": ("Դիտել բոլոր նախագծերը", "Смотреть все проекты", "View all projects"),
    "cta.allProducts": ("Դիտել ամբողջ արտադրանքը", "Смотреть всю продукцию", "View all products"),
    "cta.contact": ("Կապ հաստատել", "Связаться", "Get in touch"),
    "cta.request": ("Ուղարկել հարցում", "Отправить запрос", "Send a request"),
    "cta.discuss": ("Քննարկել նախագիծը", "Обсудить проект", "Discuss a project"),
    "cta.viewCatalog": ("Կատալոգ", "Каталог", "Catalogue"),
    "cta.download": ("Ներբեռնել", "Скачать", "Download"),
    "label.voltage": ("Լարում", "Напряжение", "Voltage"),
    "label.current": ("Հոսանք", "Ток", "Current"),
    "label.accuracy": ("Ճշտության դաս", "Класс точности", "Accuracy class"),
    "label.interfaces": ("Ինտերֆեյսներ", "Интерфейсы", "Interfaces"),
    "label.category": ("Կատեգորիա", "Категория", "Category"),
    "label.location": ("Տեղակայում", "Локация", "Location"),
    "label.client": ("Պատվիրատու", "Заказчик", "Client"),
    "label.year": ("Տարի", "Год", "Year"),
    "label.specs": ("Տեխնիկական բնութագրեր", "Технические характеристики", "Technical specifications"),
    "label.features": ("Առանձնահատկություններ", "Особенности", "Features"),
    "search.placeholder": ("Որոնել արտադրանք…", "Поиск продукции…", "Search products…"),

    "home.hero.kicker": ("Էներգետիկ ինժեներինգ · Արտադրություն · Հաշվառում", "Энергетический инжиниринг · Производство · Учёт", "Power engineering · Manufacturing · Metering"),
    "home.hero.title": ("ՓՈԽԱԿԵՐՊՈՒՄՆԵՐԻ ԷՆԵՐԳԻԱ", "ЭНЕРГИЯ ПРЕОБРАЗОВАНИЙ", "ENERGY OF TRANSFORMATIONS"),
    "home.hero.subtitle": ("Կասկադ Գրուպ — էներգետիկ օբյեկտների նախագծում և շինարարություն, միջին լարման բաշխիչ սարքերի և խելացի էլեկտրահաշվիչների արտադրություն։", "Каскад Групп — проектирование и строительство энергообъектов, производство распределительных устройств среднего напряжения и умных электросчётчиков.", "Kaskad Group — design and construction of power facilities, manufacturing of medium-voltage switchgear and smart electricity meters."),
    "home.hero.cta1": ("Մեր ուղղությունները", "Наши направления", "Our divisions"),
    "home.hero.cta2": ("Կապ հաստատել", "Связаться", "Get in touch"),

    "home.intro.kicker": ("Ընկերության մասին", "О компании", "About the company"),
    "home.intro.title": ("Էներգետիկայի ամբողջական ցիկլ՝ մեկ խմբում", "Полный цикл энергетики в одной группе", "The full energy cycle in one group"),
    "home.intro.text": ("Կասկադ Գրուպը միավորում է երեք լրացնող ուղղություններ՝ էներգետիկ ինժեներինգ և շինարարություն, միջին լարման բաշխիչ սարքերի արտադրություն և խելացի էլեկտրահաշվիչների արտադրություն։ 20+ տարվա փորձ, սեփական գործարաններ և միջազգային տեխնոլոգիաներ՝ Հայաստանից մինչև ԱՊՀ։", "Каскад Групп объединяет три взаимодополняющих направления: энергетический инжиниринг и строительство, производство распределительных устройств среднего напряжения и производство умных электросчётчиков. 20+ лет опыта, собственные заводы и международные технологии — от Армении до стран СНГ.", "Kaskad Group unites three complementary divisions: power engineering & construction, medium-voltage switchgear manufacturing, and smart electricity-meter manufacturing. 20+ years of expertise, own plants and international technology — from Armenia across the CIS."),

    "home.div.kicker": ("Երեք ուղղություն", "Три направления", "Three divisions"),
    "home.div.title": ("Մեր բիզնես ուղղությունները", "Наши бизнес-направления", "Our business divisions"),
    "home.div.construction.title": ("Շինարարություն", "Строительство", "Construction"),
    "home.div.construction.text": ("Էներգետիկ օբյեկտների նախագծում, էլեկտրամոնտաժ, գործարկում-կարգաբերում և փորձարկումներ։", "Проектирование энергообъектов, электромонтаж, пусконаладка и испытания.", "Design of power facilities, electrical installation, commissioning and testing."),
    "home.div.switchgear.title": ("Բաշխիչ սարքերի արտադրություն", "Производство распредустройств", "Switchgear manufacturing"),
    "home.div.switchgear.text": ("6–24 կՎ միջին լարման ԿՌՈՒ, КСО և КТИС մոդուլներ՝ DEBA տեխնոլոգիայով։", "Модули КРУ, КСО и КТИС среднего напряжения 6–24 кВ по технологии DEBA.", "6–24 kV medium-voltage KRU, KSO and KTiS modules built with DEBA technology."),
    "home.div.meters.title": ("Հաշվիչների արտադրություն", "Производство счётчиков", "Meter manufacturing"),
    "home.div.meters.text": ("Միաֆազ, եռաֆազ և բարձրավոլտ խելացի էլեկտրահաշվիչներ՝ AMR/AMI աջակցությամբ։", "Однофазные, трёхфазные и высоковольтные умные электросчётчики с поддержкой AMR/AMI.", "Single-phase, three-phase and high-voltage smart electricity meters with AMR/AMI support."),

    "home.projects.kicker": ("Պորտֆոլիո", "Портфолио", "Portfolio"),
    "home.projects.title": ("Ընտրված նախագծեր", "Избранные проекты", "Featured projects"),
    "home.products.kicker": ("Կատալոգ", "Каталог", "Catalogue"),
    "home.products.title": ("Ընտրված արտադրանք", "Избранная продукция", "Featured products"),
    "home.adv.kicker": ("Ինչու՞ մենք", "Почему мы", "Why us"),
    "home.adv.title": ("Ընկերության առավելությունները", "Преимущества компании", "Company advantages"),
    "home.stats.title": ("Թվերով", "В цифрах", "By the numbers"),
    "home.partners.kicker": ("Վստահում են մեզ", "Нам доверяют", "Trusted by"),
    "home.partners.title": ("Գործընկերներ և հաճախորդներ", "Партнёры и клиенты", "Partners & clients"),
    "home.news.kicker": ("Նորություններ", "Новости", "News"),
    "home.news.title": ("Վերջին նորությունները", "Последние новости", "Latest news"),
    "home.contact.kicker": ("Կապ", "Контакты", "Contact"),
    "home.contact.title": ("Եկեք քննարկենք ձեր նախագիծը", "Давайте обсудим ваш проект", "Let’s discuss your project"),

    "constr.hero.title": ("ՇԻՆԱՐԱՐՈՒԹՅՈՒՆ ԵՎ ԻՆԺԵՆԵՐԻՆԳ", "СТРОИТЕЛЬСТВО И ИНЖИНИРИНГ", "CONSTRUCTION & ENGINEERING"),
    "constr.hero.subtitle": ("Էներգետիկ օբյեկտների ամբողջական ցիկլ՝ նախագծումից մինչև շահագործման հանձնում։", "Полный цикл работ на энергообъектах — от проектирования до ввода в эксплуатацию.", "Full-cycle work on power facilities — from design to commissioning."),
    "constr.services.title": ("Ծառայություններ", "Услуги", "Services"),
    "constr.projects.title": ("Նախագծեր", "Проекты", "Projects"),
    "constr.gallery.title": ("Պատկերասրահ", "Галерея", "Gallery"),
    "constr.clients.title": ("Մեր հաճախորդները", "Наши клиенты", "Our clients"),
    "constr.tech.title": ("Տեխնիկական տեղեկատվություն", "Техническая информация", "Technical information"),
    "constr.tech.text": ("Աշխատում ենք մինչև 110 կՎ և ավելի լարման դասերի հետ՝ ենթակայաններ 220/110/10 կՎ, 35/6 կՎ, ՌՊԱ, ԱՍԿՈՒԷ, ԱՎՀ, մալուխային և օդային գծեր, հողանցում և կայծակնապաշտպանություն։", "Работаем с классами напряжения до 110 кВ и выше: подстанции 220/110/10 кВ, 35/6 кВ, РЗА, АСКУЭ, АСУ ТП, кабельные и воздушные линии, заземление и молниезащита.", "We work with voltage classes up to 110 kV and above: 220/110/10 kV and 35/6 kV substations, relay protection & automation, metering (AMR/AMI), SCADA, cable and overhead lines, earthing and lightning protection."),

    "sw.hero.title": ("ԲԱՇԽԻՉ ՍԱՐՔԵՐԻ ԱՐՏԱԴՐՈՒԹՅՈՒՆ", "ПРОИЗВОДСТВО РАСПРЕДУСТРОЙСТВ", "SWITCHGEAR MANUFACTURING"),
    "sw.hero.subtitle": ("6–24 կՎ միջին լարման ամբողջական բաշխիչ սարքեր՝ Բելգիական DEBA տեխնոլոգիայով։", "Комплектные распределительные устройства среднего напряжения 6–24 кВ по технологии бельгийской компании DEBA.", "Complete medium-voltage switchgear 6–24 kV built with the technology of the Belgian company DEBA."),
    "sw.catalog.title": ("Արտադրանքի կատալոգ", "Каталог продукции", "Product catalogue"),
    "sw.process.title": ("Արտադրության գործընթաց", "Производственный процесс", "Manufacturing process"),
    "sw.gallery.title": ("Պատկերասրահ", "Галерея", "Gallery"),
    "sw.specs.title": ("Տեխնիկական բնութագրեր", "Технические характеристики", "Technical specifications"),

    "mt.hero.title": ("ԷԼԵԿՏՐԱՀԱՇՎԻՉՆԵՐԻ ԱՐՏԱԴՐՈՒԹՅՈՒՆ", "ПРОИЗВОДСТВО ЭЛЕКТРОСЧЁТЧИКОВ", "ELECTRICITY METER MANUFACTURING"),
    "mt.hero.subtitle": ("Խելացի միաֆազ, եռաֆազ և բարձրավոլտ էլեկտրաէներգիայի հաշվիչներ։", "Умные однофазные, трёхфазные и высоковольтные счётчики электроэнергии.", "Smart single-phase, three-phase and high-voltage electricity meters."),
    "mt.catalog.title": ("Հաշվիչների կատալոգ", "Каталог счётчиков", "Meter catalogue"),
    "mt.tech.title": ("Տեխնոլոգիաներ", "Технологии", "Technology"),
    "mt.docs.title": ("Տեխնիկական փաստաթղթեր", "Техническая документация", "Technical documentation"),
    "mt.compare.title": ("Արտադրանքի համեմատություն", "Сравнение продукции", "Product comparison"),
    "mt.gallery.title": ("Պատկերասրահ", "Галерея", "Gallery"),
    "mt.compare.model": ("Մոդել", "Модель", "Model"),
    "mt.compare.type": ("Տեսակ", "Тип", "Type"),
    "mt.compare.accuracy": ("Ճշտություն", "Точность", "Accuracy"),
    "mt.compare.current": ("Հոսանք", "Ток", "Current"),
    "mt.compare.interfaces": ("Ինտերֆեյսներ", "Интерфейсы", "Interfaces"),

    "about.hero.title": ("ՄԵՐ ՄԱՍԻՆ", "О КОМПАНИИ", "ABOUT US"),
    "about.hero.subtitle": ("Կասկադ Գրուպ — էներգիայի փոխակերպման ինժեներինգ և արտադրություն։", "Каскад Групп — инжиниринг и производство для энергии преобразований.", "Kaskad Group — engineering and manufacturing for the energy of transformations."),
    "about.history.title": ("Ընկերության պատմություն", "История компании", "Company history"),
    "about.mission.title": ("Առաքելություն", "Миссия", "Mission"),
    "about.mission.text": ("Ներդնել առաջադեմ եվրոպական տեխնոլոգիաներ էներգետիկ ենթակառուցվածքում՝ ապահովելով հուսալի, անվտանգ և արդյունավետ էներգամատակարարում։", "Внедрять передовые европейские технологии в энергетическую инфраструктуру, обеспечивая надёжное, безопасное и эффективное энергоснабжение.", "To bring advanced European technology into energy infrastructure, ensuring reliable, safe and efficient power supply."),
    "about.vision.title": ("Տեսլական", "Видение", "Vision"),
    "about.vision.text": ("Դառնալ տարածաշրջանի առաջատար էներգետիկ խումբը՝ ինժեներինգից մինչև խելացի հաշվառում ամբողջական լուծումներով։", "Стать ведущей энергетической группой региона с комплексными решениями — от инжиниринга до умного учёта.", "To become the region’s leading energy group with end-to-end solutions — from engineering to smart metering."),
    "about.values.title": ("Արժեքներ", "Ценности", "Values"),
    "about.certs.title": ("Սերտիֆիկատներ", "Сертификаты", "Certificates"),
    "about.partners.title": ("Գործընկերներ", "Партнёры", "Partners"),

    "projects.hero.title": ("ՆԱԽԱԳԾԵՐ", "ПРОЕКТЫ", "PROJECTS"),
    "projects.hero.subtitle": ("Էներգետիկ ենթակառուցվածքի իրականացված նախագծեր Հայաստանում և ԱՊՀ-ում։", "Реализованные проекты энергетической инфраструктуры в Армении и СНГ.", "Completed power-infrastructure projects across Armenia and the CIS."),
    "projects.filter.title": ("Զտել ըստ կատեգորիայի", "Фильтр по категории", "Filter by category"),

    "products.hero.title": ("ԱՐՏԱԴՐԱՆՔ", "ПРОДУКЦИЯ", "PRODUCTS"),
    "products.hero.subtitle": ("Բաշխիչ սարքեր և էլեկտրահաշվիչներ մեկ կատալոգում։", "Распределительные устройства и электросчётчики в едином каталоге.", "Switchgear and electricity meters in a single catalogue."),
    "products.filter.all": ("Բոլորը", "Все", "All"),
    "products.filter.switchgear": ("Բաշխիչ սարքեր", "Распредустройства", "Switchgear"),
    "products.filter.meters": ("Հաշվիչներ", "Счётчики", "Meters"),
    "products.empty": ("Ոչ մի արտադրանք չի գտնվել։", "Продукция не найдена.", "No products found."),

    "contact.hero.title": ("ԿԱՊ", "КОНТАКТЫ", "CONTACT"),
    "contact.hero.subtitle": ("Կապվեք մեզ հետ ձեր հաջորդ էներգետիկ նախագծի համար։", "Свяжитесь с нами для вашего следующего энергетического проекта.", "Reach out to us for your next power project."),
    "contact.info.title": ("Կոնտակտային տվյալներ", "Контактные данные", "Contact details"),
    "contact.address": ("Հասցե", "Адрес", "Address"),
    "contact.phone": ("Հեռախոս", "Телефон", "Phone"),
    "contact.email": ("Էլ. փոստ", "Эл. почта", "Email"),
    "contact.form.title": ("Գրեք մեզ", "Напишите нам", "Write to us"),
    "contact.form.name": ("Անուն", "Имя", "Name"),
    "contact.form.email": ("Էլ. փոստ", "Эл. почта", "Email"),
    "contact.form.phone": ("Հեռախոս", "Телефон", "Phone"),
    "contact.form.subject": ("Թեմա", "Тема", "Subject"),
    "contact.form.message": ("Հաղորդագրություն", "Сообщение", "Message"),
    "contact.form.submit": ("Ուղարկել", "Отправить", "Send"),
    "contact.form.success": ("Շնորհակալություն։ Ձեր հաղորդագրությունն ուղարկվեց (դեմո)։", "Спасибо! Ваше сообщение отправлено (демо).", "Thank you! Your message has been sent (demo)."),
    "contact.map.title": ("Քարտեզ", "Карта", "Map"),

    "footer.about": ("Կասկադ Գրուպ — էներգետիկ ինժեներինգ, բաշխիչ սարքերի և խելացի հաշվիչների արտադրություն Երևանում։", "Каскад Групп — энергетический инжиниринг, производство распредустройств и умных счётчиков в Ереване.", "Kaskad Group — power engineering, switchgear and smart-meter manufacturing, headquartered in Yerevan."),
    "footer.divisions": ("Ուղղություններ", "Направления", "Divisions"),
    "footer.company": ("Ընկերություն", "Компания", "Company"),
    "footer.contact": ("Կապ", "Контакты", "Contact"),
    "footer.rights": ("Բոլոր իրավունքները պաշտպանված են։", "Все права защищены.", "All rights reserved."),
    "footer.langNote": ("Լեզու", "Язык", "Language"),
}
